version: "3"

services:
  api:
    image: registry.zouzland.com/adoptacutie/server:latest
    restart: always
    expose:
      - "8080"
    environment:
      VIRTUAL_HOST: adoptacutie.zouzland.com
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: adoptacutie.zouzland.com
      VIRTUAL_NETWORK: nginx-proxy

networks:
  default:
    external:
        name: nginx-proxy