version: "3"

services:
  api:
    build: .
    image: registry.zouzland.com/adoptacutie/server:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      VIRTUAL_HOST: adoptacutie.zouzland.com
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: adoptacutie.zouzland.com
      VIRTUAL_NETWORK: nginx-proxy
      MONGO_HOST: database
      MONGO_PORT: 27017
      MONGO_USERNAME: adoptacutie
      MONGO_DATABASE: adoptacutie
      MONGO_PASSWORD: NicePasswordM8
    volumes:
      - ./model.h5:/model/model.h5
      - ./test:/tmp/test
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: adoptacutie
      MONGO_INITDB_USERNAME: adoptacutie
      MONGO_INITDB_PASSWORD: NicePasswordM8
    volumes:
      - mongo-volume:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    expose:
      - 27017
      - 27018
      - 27019

volumes:
  mongo-volume:

# networks:
#   default:
#     external:
#         name: nginx-proxy