# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Color(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, label: str=None):  # noqa: E501
        """Color - a model defined in Swagger

        :param id: The id of this Color.  # noqa: E501
        :type id: int
        :param label: The label of this Color.  # noqa: E501
        :type label: str
        """
        self.swagger_types = {
            'id': int,
            'label': str
        }

        self.attribute_map = {
            'id': 'id',
            'label': 'label'
        }
        self._id = id
        self._label = label

    @classmethod
    def from_dict(cls, dikt) -> 'Color':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Color of this Color.  # noqa: E501
        :rtype: Color
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Color.


        :return: The id of this Color.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Color.


        :param id: The id of this Color.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def label(self) -> str:
        """Gets the label of this Color.


        :return: The label of this Color.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label: str):
        """Sets the label of this Color.


        :param label: The label of this Color.
        :type label: str
        """

        self._label = label
